# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemesSiteBuilder/?tab=readme-ov-file#theme-configuration for an example

name = "Material Design Blog Theme"
license = "MIT"
licenselink = "https://github.com/ams-www/material-blog-theme/tree/main/LICENSE"
description = "A blog hugo theme with Material Design 3"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/kons10/material-blog-theme"

# If you have a running demo of the theme.
demosite = "https://hugo.kto.f5.si"

tags = ["blog", "minimal"]
features = ["syntax-highlighting", "analytics"]

# If the theme has a single author
[author]
    name = "Sio"
    homepage = "https://site.kto.f5.si"

# If porting an existing theme
[original]
    author = "Junya Miyamoto"
    homepage = "https://m1yam0t0.com/"
    repo = "https://github.com/m1yam0t0/hugo-blog-theme"
